### ISSUE TITLE
question

### ISSUE THREAD

**Issue by qigemingzenmezhemenan** [liguge/1D-Grad-CAM-for-fault-diagnosis#1]
Hello, I want to do 1D grad cam related problems. The code seems to be incomplete. Can you give me a complete code?

**Comment by liguge** [comment]
The code is actually complete, please refer to the code of 1D-Grad-CAM++ to modify 1D-Grad-CAM slightly.
Or please be specific about the specific problem you are having. I will give you specific explanations and answers.



At 2022-06-22 16:25:15, "qigemingzenmezhemenan" ***@***.***> wrote:

Hello, I want to do 1D grad cam related problems. The code seems to be incomplete. Can you give me a complete code?

**Comment by qigemingzenmezhemenan** [comment]
你好，我是一名初学者，我想问的是，
在Grad-Cam++ 1d v2.py中，
model = Net1()未定义，该怎么解决。




拥有比失去更无奈°
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liguge/1D-Grad-CAM-for-interpretable-intelligent-fault-diagnosis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月22日(星期三) 下午5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liguge/1D-Grad-CAM-for-interpretable-intelligent-fault-diagnosis] question (Issue #1)





 The code is actually complete, please refer to the code of 1D-Grad-CAM++ to modify 1D-Grad-CAM slightly.
 Or please be specific about the specific problem you are having. I will give you specific explanations and answers.
 
 
 
 At 2022-06-22 16:25:15, "qigemingzenmezhemenan" ***@***.***&gt; wrote:
 
 Hello, I want to do 1D grad cam related problems. The code seems to be incomplete. Can you give me a complete code?

**Comment by qigemingzenmezhemenan** [comment]
Hello, I am a beginner. What I want to ask is,

In grad cam++ 1D v2.Py,

Model = net1() is undefined. How to solve it.Hello, I am a beginner. What I want to ask is,

In grad cam++ 1D v2 Py,

Model = net1() is undefined. How to solve it.

**Comment by liguge** [comment]
This line is to load a model that  your own designs. This code is to verify the quality of the model designed by itself, and it cannot be run directly. After loading your own model, you also need to load the pretrained weights. In this case, the code can normally run.













At 2022-06-22 20:37:42, "qigemingzenmezhemenan" ***@***.***> wrote:

Hello, I am a beginner. What I want to ask is,

In grad cam++ 1D v2.Py,

Model = net1() is undefined. How to solve it.Hello, I am a beginner. What I want to ask is,

In grad cam++ 1D v2 Py,

Model = net1() is undefined. How to solve it.

**Comment by liguge** [comment]
net1 refers to the name of the network I designed myself called net1.










在 2022-06-22 18:36:23，"qigemingzenmezhemenan" ***@***.***> 写道：

你好，我是一名初学者，我想问的是，
在Grad-Cam++ 1d v2.py中，
model = Net1()未定义，该怎么解决。




拥有比失去更无奈°
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liguge/1D-Grad-CAM-for-interpretable-intelligent-fault-diagnosis" ***@***.***&gt;;
发送时间:&nbsp;2022年6月22日(星期三) 下午5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liguge/1D-Grad-CAM-for-interpretable-intelligent-fault-diagnosis] question (Issue #1)





The code is actually complete, please refer to the code of 1D-Grad-CAM++ to modify 1D-Grad-CAM slightly.
Or please be specific about the specific problem you are having. I will give you specific explanations and answers.



At 2022-06-22 16:25:15, "qigemingzenmezhemenan" ***@***.***&gt; wrote:

Hello, I want to do 1D grad cam related problems. The code seems to be incomplete. Can you give me a complete code?

**Comment by qigemingzenmezhemenan** [comment]
OK, thank you for your answer.




拥有比失去更无奈°
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liguge/1D-Grad-CAM-for-interpretable-intelligent-fault-diagnosis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月22日(星期三) 晚上10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liguge/1D-Grad-CAM-for-interpretable-intelligent-fault-diagnosis] question (Issue #1)





 
 
 
 This line is to load a model that  your own designs. This code is to verify the quality of the model designed by itself, and it cannot be run directly. After loading your own model, you also need to load the pretrained weights. In this case, the code can normally run.
 
 
 
 
 
 
 
 
 
 
 
 
 
 At 2022-06-22 20:37:42, "qigemingzenmezhemenan" ***@***.***&gt; wrote:
 
 Hello, I am a beginner. What I want to ask is,
 
 In grad cam++ 1D v2.Py,
 
 Model = net1() is undefined. How to solve it.Hello, I am a beginner. What I want to ask is,
 
 In grad cam++ 1D v2 Py,
 
 Model = net1() is undefined. How to solve it.

**Comment by liguge** [comment]
The code is actually complete, please refer to the code of 1D-Grad-CAM++ to modify 1D-Grad-CAM slightly.

Or please be specific about the specific problem you&#39;re having. I will give you specific explanations and answers.










At 2022-06-22 16:25:15, "qigemingzenmezhemenan" ***@***.***> wrote:

Hello, I want to do 1D grad cam related problems. The code seems to be incomplete. Can you give me a complete code?
